### ISSUE TITLE
Use as background / container for React components ?

### ISSUE THREAD

**Issue by revskill10** [mvilledieu/shadertoy-react#4]
Could i put `children` inside shadertoy-react to have background ?

**Comment by mvilledieu** [comment]
What kind of background do you need?

If you are willing to get a classic `background:` in CSS just pass a style uniform to your component this way:

`<ShadertoyReact style={{ background: "red" }} fs={fragmentShader} />`

Just make sure to pass an alpha value to your `gl_FragColor = vec4(r, g, b, a);`

The other way of having a background is to directly render the background image or color in your shader and don't have a transparent shader.

**Comment by Jarred-Sumner** [comment]
@revskill10 -- you can wrap it in a container and then set the ShaderToy component to `position: absolute` with a `z-index` of `0` and then the text with a `z-index` of `1`

![image](https://user-images.githubusercontent.com/709451/55847160-1e1db580-5afd-11e9-8deb-9b69691abba6.png)
